// create space api
// TODO: take the below and spit a autogenerated space
export type Space = {
  spaceName: string;
  logo: string;
  isSquare: boolean;
  title: string;
  message: string;
  questions: string[];
  linksToCollect: {
    title: boolean;
    company: boolean;
    socialLink: boolean;
  };
  theme: Theme;
  shouldCollectStars: boolean;
  collectionType: CollectionType;
  customButtonColor: string;
};

export enum Languages {
  "ENGLISH" = "English",
}

export enum CollectionType {
  TEXT_AND_VIDEO = "TEXT_AND_VIDEO",
  TEXT = "TEXT",
  VIDEO = "VIDEO",
}

export enum Theme {
  DARK = "dark",
  LIGHT = "light",
}

// send testimonial from user via link
// take link spaceName and save testimonial information
export type TextTestimonial = {
  stars: number;
  reviewMessage: string;
  reviewImage: string;
  name: string;
  email: string;
  titleAndCompany: string;
  socialLink: string;
  address: string;
  userImage: string;
  consent: boolean;
};
